### ISSUE TITLE
RocketChat app still looking for '+'

### ISSUE THREAD

**Issue by krispayne** [autopkg/apizz-recipes#15]
The package recipe is still looking for '+' in the app name:

https://github.com/autopkg/apizz-recipes/blob/master/RocketChat/RocketChatClient.pkg.recipe#L61

Looks like this was updated in the download recipe a few days ago.

**Comment by apizz** [comment]
Thanks for catching this.  Just updated

**Comment by krispayne** [comment]
👍 will test later today. Working on postinstall scripts for rocket chat now :-)

**Comment by krispayne** [comment]
Hmm, I might be missing something. I thought the PKG recipe was making a PKG from the download recipe. It's simply downloading the PKG version of the release (which is fine!)

However, I made an override, updated the trust, removed all previous items downloaded, and then ran the recipe:

```    RocketChatClient.pkg
        Error in local.pkg.RocketChatClient: Processor: CodeSignatureVerifier: Error: Error processing path '/Users/autopkg/Library/AutoPkg/Cache/local.pkg.RocketChatClient/downloads/RocketChatClient-2.17.0.pkg/Rocket.Chat.app' with glob.```

does https://github.com/autopkg/apizz-recipes/blob/master/RocketChat/RocketChatClient.pkg.recipe#L60-L62 need to be in this recipe? The + sign might have been a fallacy bug and the real bug is that this part doesn't need to occur? Looks like it was maybe part of the DMG recipe?

**Comment by krispayne** [comment]
Hmm maybe not remove it, but a different value? I'm resting some data now

**Comment by krispayne** [comment]
Yup, I removed the App name and it runs now

```
                <key>input_path</key>
                <string>%pathname%</string>
```

**Comment by apizz** [comment]
That should do it!

**Comment by krispayne** [comment]
Cool, thanks!
