### ISSUE TITLE
AutodeskMaya2020Import.munki.recipe post install script fails in munki

### ISSUE THREAD

**Issue by jaw4uz** [autopkg/apizz-recipes#23]
The install fails in munki due to Autodesk moving the location of the setup binary on the maya2020.app. After running the recipe in autopkg and importing Maya 2020 into munki I ran a test install on a computer and the install failed with the following errors 

/tmp/munki-d2sl262t/postinstall_script: line 24: /tmp/Install Maya 2020.app/Contents/MacOS/setup: No such file or directory
/tmp/munki-d2sl262t/postinstall_script: line 29: /tmp/Install Maya 2020.app/Contents/Resources/adlmreg: No such file or directory.

It looks like in the Install Maya 2020.app Autodesk has moved the location of the setup binary from "Contents/MacOS/setup" to "Contents/Helper/Setup.app/Contents/MacOS/Setup"

I'm not sure where the adlmreg has been moved to I wasn't able to find that

**Comment by apizz** [comment]
Thanks for reporting!

I also recently relearned that Maya only includes the updated app version (including service pack) in the pkg receipt and that app's `CFBundleShortVersionString` and `CFBundleVersion` is always 2020.  So the munki recipe itself needs some additional attention.

In a bit of a transition now, but I will try and address this in the next week or so.

**Comment by jaw4uz** [comment]
Thanks this recipe is a huge help I've been creating manual munki pkginfo files for Maya and Mudbox for the last 3 years

**Comment by apizz** [comment]
Update: In my testing today I was able to get Maya into a desired state in my munki_repo.  Autodesk made a lot of changes to the deployment process (moving the setup executable, the CLI for silent installation, as well as now having a deployment.xml file which is used to determine what to install) and while it does install successfully, it does not install my standalone license as I would expect such that on first launch it's ready to go.

ATM, the Autodesk docs indicate using the following - `/path/to/Setup --install_type deploy --silent --deployment /path/to/deployment.xml` -, but this causes an error during install.  Removing the `-install_type deploy` successfully installs, but again does not install license.

So progress, but not 100% ready ...

**Comment by apizz** [comment]
OK, so I think I have this working.  I naively assumed the `postinstall_script` would carry over from 2019, but Autodesk made changes, of course ...

Can you please give the version I have in my maya-patch branch a try and make sure the import into your munki_repo works as expected, as well as installs and uninstalls correctly? - https://github.com/autopkg/apizz-recipes/blob/maya-patch/Autodesk/AutodeskMaya2020Import.munki.recipe

**Comment by apizz** [comment]
Verified desired end result in my own testing.

**Comment by apizz** [comment]
Detailed update here: https://aporlebeke.wordpress.com/2020/07/14/automating-manual-munki-imports-with-autopkg-part-2-autodesk-maya/

**Comment by jaw4uz** [comment]
In my testing the recipe worked as expected this saves me a ton of time and work thanks

**Comment by apizz** [comment]
Awesome, I'm so glad to hear. I recently left my last job and this was a bit of a present before I left because no one else was writing recipes ...
