### ISSUE TITLE
Deprecating my RocketChat recipes

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/apizz-recipes#26]
I am going to depracate my RocketChat [recipes](https://github.com/autopkg/MichalMMac-recipes/tree/master/RocketChat) in favor of yours. We are not using RocketChat much anymore and I don't see a point to have a duplicate in AutoPkg search. Download from website no longer works the same way so they are broken anyway.

Is it ok I add link to your recipes in deprecation warning?

**Comment by apizz** [comment]
Go for it

**Comment by MichalMMac** [comment]
Ok. Thanks.
