### ISSUE TITLE
FileMakerAdvanced.munki.recipe download/import issue

### ISSUE THREAD

**Issue by ewtillman** [autopkg/apizz-recipes#28]
I have added my custom search_url fine per instructions. I needed to also update the major_version to 19 and search_pattern because the url/filename changed to https://downloads.claris.com/esd/fmp_19.0.1.116.dmg

So far it looks like this works, finds the correct file, downloads it but its not importing into munki.

I am getting Error processing path '/private/tmp/dmg.3RohqW/*.pkg' with glob.

Any help would be much appreciated.

**Comment by apizz** [comment]
Thanks for reporting. I'll take a look

**Comment by apizz** [comment]
Sorry this has taken me longer to review @ewtillman.  I've created two recipes in my repo: https://github.com/autopkg/apizz-recipes/tree/master/FileMaker.  Let me know if you run into any issues.
