### ISSUE TITLE
question regarding ChromeRemoteDesktop.munki

### ISSUE THREAD

**Issue by jgengo** [autopkg/apizz-recipes#32]
It's more a question than an issue I guess,

I've run the ChromeRemoteDesktop.munki without any trouble, I'm able to find chrome remote desktop inside my munki repo.

A question tho when I run chrome and try to access chrome remote desktop it says: 

```
Set up remote desktop access
A problem was detected with the chrome remote desktop installation on this computer.
```

Do you have any idea why this happens?

**Comment by apizz** [comment]
No idea. I just make sure the thing downloads & imports into munki with autopkg 😄

**Comment by jgengo** [comment]
alright @apizz thank you :)
