### ISSUE TITLE
VSCodium.download not pulling down latest, likely due to change in .dmg naming scheme

### ISSUE THREAD

**Issue by fseesink** [autopkg/apizz-recipes#36]
`VSCodium.download` appears to be stuck at v1.51.1 when current version is v1.52.1.  I checked and v1.51.1 was the last version of VSCodium's GitHub repo to use the naming scheme for binaries resulting in a filename like `VSCodium.1.51.1.dmg`.

Beginning with v1.52.0, they're now using a naming scheme such as `VSCodium.x64.1.52.0.dmg`.  This is likely due to Apple's recent release of their Apple Silicon M1-based Macs, to distinguish whether a binary is x64, ARM64, or a Universal Binary2.

The issue appears to be with the RegEx pattern used in the download recipe:
```
...
                <key>asset_regex</key>
                <string>^VSCodium.[\d.]+.dmg$</string>
...
```
This likely needs to be tweaked to something like
```
...
                <key>asset_regex</key>
                <string>^VSCodium\.x64\.[\d.]+\.dmg$</string>
...
```
(NOTE:  I also added backslashes before the periods, as the current RegEx isn't actually matching on those periods but rather simply a single character in that position, which happens to be a period.)

Of course, this may need to be adjusted in the future if they offer either a Universal Binary2 or an ARM64 binary.  But this what I see for now.

**Comment by apizz** [comment]
Thanks for this.  I've addressed this in https://github.com/autopkg/apizz-recipes/commit/8a660f11c831b22e58d9d832836f850f3724a300
