### ISSUE TITLE
Vectorworks2021

### ISSUE THREAD

**Issue by xastherion** [autopkg/apizz-recipes#38]
Hello Apizz
Have you in plan to deploy a new recipe for the 2021 version? 
The actual version for 2020 allow only the serial version, how can i change it as "demo" or test mode, and how it is posible for "Viewer" too?
Thanks a lot for this recipe.

Xasthe

**Comment by apizz** [comment]
I no longer work with the software unfortunately after switching jobs, so if there is no network option or other things need to be changed feel free to use this recipe as a base for any recipe you might create.

**Comment by xastherion** [comment]
Oh, sadly (for me). Sure, i hope i can still ask you some things about it! 
Thanks again!

**Comment by apizz** [comment]
Happy to help if I'm able. If it's generally about autopkg though, you may find the MacAdmins #autopkg channel a more helpful resource.
