### ISSUE TITLE
hdutil create issue

### ISSUE THREAD

**Issue by TechJedi51** [autopkg/apizz-recipes#39]
I am getting the following error: 

`Error in local.munki.MakeMKV: Processor: DmgCreator: Error: creation of /pathname/AutoPkg/Cache/local.munki.MakeMKV/MakeMKV.dmg failed: hdiutil: create failed - No space left on device
`
It may be similar to this issue:
https://github.com/autopkg/jps3-recipes/issues/57

**Comment by apizz** [comment]
Thanks for reporting I'll have a look as soon as I'm able

**Comment by TechJedi51** [comment]
No worries. Thanks for maintaining this recipe. Much appreciated.

**Comment by apizz** [comment]
OK, this should be resolved now with https://github.com/autopkg/apizz-recipes/commit/15e019389240f00870b7845612cbc652172bfc64.

It appears we no longer need to create a separate DMG (I can't recall why this was needed in the first place) but had I just increased the configured DMG size that would have also addressed this.  Still, never a bad idea to review what you've done before and make improvements!

This will produce a cleaner version number for the munki item (`1.16.3`), albeit the app has a `CFBundleShortVersionString` value of something like `v1.16.3`.  You'll need `homebysix`'s repo for the `VersionSplitter` processor.

![Screen Shot 2021-03-19 at 8 09 01 PM](https://user-images.githubusercontent.com/11789931/111853118-0279d700-88f0-11eb-911a-37b448348b67.png)
![Screen Shot 2021-03-19 at 8 08 57 PM](https://user-images.githubusercontent.com/11789931/111853122-04dc3100-88f0-11eb-9402-ddcaf089d3d7.png)

**Comment by TechJedi51** [comment]
That worked great. Thanks again.

I sometimes go back and review code I have written and wonder why I took the long way around something. Sometimes, but not always, I add a comment or two explaining the "why". I need to get better at doing that.
