### ISSUE TITLE
hdiutil create failed - no space left on device

### ISSUE THREAD

**Issue by ctange3** [autopkg/apizz-recipes#42]
Hello! I'm getting an error similar to issue #39 but for GeoGebra6.

`Error in local.munki.GeoGebra6: Processor: DmgCreator: Error: creation of /path/local.munki.GeoGebra6/GeoGebra6.dmg failed: hdiutil: create failed - No space left on device`

**Comment by apizz** [comment]
Hmm, can you confirm you're seeing something when you go to https://download.geogebra.org/package/mac-port ?  I get redirected to https://download.geogebra.org/installers/6.0/GeoGebra-Classic-6-MacOS-Portable-6-0-637-0.zip but then get an NGINX 404 not found error.

I can up the size of the DMG, but if the item is no longer accessible from the vendor's website, will need to reach out to them about that.

**Comment by ctange3** [comment]
You're right, it looks like it's putting out a 404 error now. Thanks for taking a look into this!

**Comment by apizz** [comment]
I'll deprecate this recipe tonight. Maybe it comes back?

**Comment by apizz** [comment]
https://github.com/autopkg/apizz-recipes/commit/c957a6ad43be17549cd9a8f4854be01cd8b2ea7b
