### ISSUE TITLE
URL has changed

### ISSUE THREAD

**Issue by prausch** [autopkg/apizz-recipes#46]
URL changed ..."software"... now ..."software-support"...

https://www.kensington.com/siteassets/software-support/kensingtonworks/new-kensingtonworks-download/kensingtonworks_2.2.11_1625821254.pkg

**Comment by apizz** [comment]
Thanks for reporting!  It looks like it wasn't the fact that the URL path changed but the filename format had added an extra _<long_interger> just before the `.pkg` extension.  Just updated with https://github.com/autopkg/apizz-recipes/commit/8e9270becb27df9754462b576e20ee5ab5f19f22.  Pull latest repo and let me know if you have issues!  With updated regex confirmed downloaded OK for me.
