### ISSUE TITLE
TuxeraNTFS.download.recipe

### ISSUE THREAD

**Issue by PeetMcK** [autopkg/apizz-recipes#52]
The scraped link on "https://www.tuxera.com/products/tuxera-ntfs-for-mac/download/" isn't for the current release of NTFS for Mac. 

Either "https://ntfsformac.tuxera.com" or "https://ntfsformac.tuxera.com/support/" include a link to the latest version ... "https://tuxera.com/mac/tuxerantfs_2020.2.dmg".

Oddly "https://ntfsformac.tuxera.com" includes "https://download.tuxera.com/mac/tuxerantfs_2020.2.dmg" and "https://tuxera.com/mac/tuxerantfs_2020.2.dmg", which makes me lean toward saying "https://ntfsformac.tuxera.com/support/" is likely the more stable page to scrape ¯\_(ツ)_/¯.

**Comment by apizz** [comment]
Thanks for this.  URL is updated to scrape version from https://ntfsformac.tuxera.com/support/.  Addressed in https://github.com/autopkg/apizz-recipes/commit/0e693c598f879eaa0d035bd7ff403f09e216c347
