### ISSUE TITLE
appleLoops.munki.recipe Parent Recipe not found

### ISSUE THREAD

**Issue by walkintom** [autopkg/apizz-recipes#6]
`Could not find parent recipe for com.github.apizz.munki.appleLoops`
`No valid recipe found for com.github.apizz.munki.appleLoops`

As appleLoops has entered its third major version, the naming convention has dropped the uppercase L, so it looks like the recipe no longer recognises its parent, whose identifier has also been updated to reflect the updated name `com.github.novaksam.pkg.appleloops`.

Link to updated parent recipe: https://github.com/autopkg/novaksam-recipes/blob/master/Recipes%20-%20pkg/appleLoops.pkg.recipe

**Comment by apizz** [comment]
Thanks @walkintom .  I had taken a quick look at this with the release of v3.0.0, but couldn't figure out the issue.  This has been resolved as of my latest commits 1ca309f3eefa923d01795e2a1e9284051164b209
