### ISSUE TITLE
Error running Google Drive autopkg recipe due to update in Python

### ISSUE THREAD

**Issue by mtconleyuk** [autopkg/apizz-recipes#62]
Received the following error running my Autopkg recipe for Google Drive:-

WARNING: /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes/GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py: cannot import name 'readPlist' from 'plistlib' (/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/plistlib.py)
Failed.

This happened after upgrading to the new version of autopkg.

AutoPkg now uses Python 3.10.6, and PyObjc 8.5. Python 3.10 brings several new general improvements and may result in some warnings or errors in processors still using some legacy Python2-conversion-to-3-isms. Please file appropriate issues with recipe authors or bring it to our attention in #autopkg in Slack.
https://github.com/autopkg/autopkg/releases/tag/v2.7

**Comment by apizz** [comment]
As you can see from the output, this is a shared processor from another autopkg author's repo. Please file with them.

**Comment by mtconleyuk** [comment]
Ah, yes. Sorry about that.
