### ISSUE TITLE
teamviewer failing

### ISSUE THREAD

**Issue by OvrAp3x** [autopkg/apizz-recipes#74]
the teamviewer pkg fails building https://github.com/autopkg/apizz-recipes/blob/master/TeamViewer/TeamViewerHostCustom15.pkg.recipe

I tried opening and installing the downloaded pkg manually and it works, but the unpacked pkg's all fail running when opened manually.

This is the error
![image](https://user-images.githubusercontent.com/14344702/204742503-cd20c7ef-41bc-4218-94f6-152102bd8c06.png)

**Comment by mtconleyuk** [comment]
This happens with the GoogleDrive recipe as well; same error message.

**Comment by apizz** [comment]
This is related to https://github.com/autopkg/autopkg/pull/804 and not a function of the recipes themselves.

**Comment by apizz** [comment]
@OvrAp3x & @mtconleyuk this should be resolved in the latest version of autopkg: `2.7.2`

**Comment by mtconleyuk** [comment]
Yes this appears to be working now with 2.7.2.
