### ISSUE TITLE
CrowdstrikeFalcon.munki.recipe failing (no longer bundles kext?)

### ISSUE THREAD

**Issue by fuzzylogiq** [autopkg/apizz-recipes#76]
Hi,

`Error in local.munki.CrowdStrikeFalcon: Processor: PkgPayloadUnpacker: Error: extraction of /Users/runner/Library/AutoPkg/Cache/local.munki.CrowdStrikeFalcon/unpack/sensor-kext.pkg/Payload with ditto failed: ditto: /Users/runner/Library/AutoPkg/Cache/local.munki.CrowdStrikeFalcon/unpack/sensor-kext.pkg/Payload: No such file or directory`

Here's the offending lines:
https://github.com/autopkg/apizz-recipes/blob/a9835dd48d6b40de371d5a5c28eed136330536cc/CrowdStrike/CrowdStrikeFalcon.munki.recipe#L148-L149

I do not think recent versions of the sensor contain the kext any more, but do not know if this can be made optional in the recipe or not...

**Comment by apizz** [comment]
Catalina support has been dropped so you're right that should probably should just be removed entirely.

**Comment by apizz** [comment]
Addressed in #79
