### ISSUE TITLE
Tailscale pkg recipe contains incorrect app path

### ISSUE THREAD

**Issue by wegotoeleven** [autopkg/apizz-recipes#85]
The `plistreader` processor in the Tailscale pkg recipe contains an incorrect path: `<string>%pathname%/RedisInsight*.app/Contents/Info.plist</string>`
This should read:
`<string>%pathname%/Tailscale.app/Contents/Info.plist</string>`

**Comment by apizz** [comment]
Fixed in ab3ea56ca8e3bdba1e2cce5351642ef639222a93
